# Default values for loft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default value is: loftsh/loft:{{ .Chart.Version }}
# image: loftsh/loft

config: # Values for loft configmap
  auth: {}
  oidc: {}

admin:
  create: true
  username: admin
  name: admin
  password: "" # leave empty to generate password reset link
  accessKeySecret: loft-user-accesskey-admin

ingress:
  enabled: true
  name: loft-ingress
  host: loft.mydomain.tld
  path: /
  tls:
    enabled: true
    secret: tls-loft
    clusterIssuer: lets-encrypt-http-issuer

service:
  type: ClusterIP
  manager:
    port: 80
    targetPort: 8080

replicaCount: 1

resources:
  requests:
    memory: 128Mi
    cpu: 50m

apiService:
  enabled: true

serviceAccount:
  name: loft
  create: true
  clusterRole: cluster-admin

nameOverride: ""
fullnameOverride: ""

certIssuer:
  create: true
  email: "" # This is a required field if create == true
  name: lets-encrypt-http-issuer
  secretName: loft-letsencrypt-credentials
  server: https://acme-v02.api.letsencrypt.org/directory
  httpResolver:
    enabled: true
    ingressClass: nginx
  resolvers: []
